Grouped per-commit actions in a single YML file; rename files and workflows slightly

diff --git a/.github/workflows/on_commit.yml b/.github/workflows/on_commit.yml
--- a/.github/workflows/on_commit.yml
+++ b/.github/workflows/on_commit.yml
@@ -1,4 +1,4 @@
-name: CI
+name: On commit
 
 on: [push]
 
@@ -8,7 +8,10 @@ permissions:
   pull-requests: write
 
 jobs:
-  build:
+  ##########################################
+  # TESTING OF THE FRAMEWORK
+  ##########################################
+  testing:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
@@ -16,7 +19,6 @@ jobs:
         python-version: [
           "3.12"
         ]
-
     steps:
       - uses: actions/checkout@v4
       - name: Set up Python ${{ matrix.python-version }}
@@ -52,15 +54,16 @@ jobs:
           token: ${{ secrets.CODECOV_TOKEN }}
           verbose: true
 
-#todo upload test reports even in case of failure?
       - name: Upload XML test report
         uses: actions/upload-artifact@v4
+        if: success() || failure()
         with:
           name: test_report_${{matrix.os}}__${{ matrix.python-version }}__${{ github.event_name }}.xml
           path: ./test_report.xml
 
       - name: Upload HTML test report
         uses: actions/upload-artifact@v4
+        if: success() || failure()
         with:
           name: test_report_${{matrix.os}}__${{ matrix.python-version }}__${{ github.event_name }}.html
           path: ./test_report.html
@@ -70,18 +73,77 @@ jobs:
         with:
           name: coverage_${{matrix.os}}__${{ matrix.python-version }}__${{ github.event_name }}
           path: coverage/
-# TODO reenable it
-#      - name: Publish coverage reports
-#        uses: irongut/CodeCoverageSummary@v1.3.0
-#        if: matrix.os == 'ubuntu-latest'
-#        with:
-#          filename: ./coverage.xml
-#          badge: true
-#          format: markdown
-#          output: both
-#      - name: Add Coverage PR Comment
-#        uses: marocchino/sticky-pull-request-comment@v2
-#        if: github.event_name == 'pull_request' && matrix.os == 'ubuntu-latest'
-#        with:
-#          recreate: true
-#          path: code-coverage-results.md
+
+  ##########################################
+  # TESTING OF THE EXAMPLE PROJECTS
+  ##########################################
+  calculator:
+    runs-on: ${{ matrix.os }}
+    defaults:
+      run:
+        shell: bash
+        working-directory: ./calculator
+    strategy:
+      matrix:
+        os: [ ubuntu-latest, macos-latest ] # somehow windows-latest is failing; dont have time for that, *nixes work
+        python-version: [
+          "3.12"
+        ]
+
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Install requirements
+        run: |
+          ./setup.sh
+      - name: Run E2E tests
+        run: |
+          ./test.sh
+  
+
+  ##########################################
+  # LINTING OF THE WHOLE CODEBASE
+  ##########################################
+  linting:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up Python 3.12
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.12
+      - name: Install requirements
+        run: |
+          [ -f ./build-requirements.txt ] && pip install -r ./build-requirements.txt || echo "No build-requirements.txt found"
+          [ -f ./requirements.txt ] && pip install -r ./requirements.txt || echo "No requirements.txt found"
+          [ -f ./test-requirements.txt ] && pip install -r ./test-requirements.txt || echo "No test-requirements.txt found"
+
+      - name: Run linter
+        run: |
+          ./run_lint.sh
+
+      - name: Upload linter text report
+        uses: actions/upload-artifact@v4
+        with:
+          name: lint_report.txt
+          path: ./lint_report.txt
+
+      - name: Upload linter XMLUnit report
+        uses: actions/upload-artifact@v4
+        with:
+          name: lint_report.xml
+          path: ./lint_report.xml
+
+
+      - name: Publish linter report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()
+        with:
+          name: Linter report
+          path: ./lint_report.xml
+          reporter: java-junit
+          fail-on-error: false
